language: csharp
dist: xenial
dotnet: 3.1
mono: none
addons:
  apt:
    packages:
      - make
      - gcc
      - libunwind8
      - libssl-dev
      - unzip
      - gettext
      - libcurl4-openssl-dev
      - libicu-dev
      - zlib1g
script:
- ". ./build.sh"