language: csharp
dist: trusty
dotnet: 1.0.0-preview2-003131
mono:
- 4.0.5
addons:
  apt:
    packages:
      - make
      - gcc
      - libunwind8
      - libssl-dev
      - unzip
      - gettext
      - libcurl4-openssl-dev
      - libicu-dev
      - zlib1g
sudo: required
script:
- ". ./build.sh"